apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-web.fullname" . }}-content
  namespace: {{ .Values.namespace.name | quote }}
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8"/>
        <title>{{ .Values.content.title }}</title>
      </head>
      <body>
        <h1>{{ .Values.content.title }}</h1>
        <p>{{ .Values.content.body }}</p>
      </body>
    </html>
