apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-web.fullname" . }}
  namespace: {{ .Values.namespace.name | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "simple-web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
